### PR TITLE
README: Add LGTM

### PR DESCRIPTION
**Pull request by luzpaz**
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/163

### CODE REVIEW

**Comment by luzpaz** [comment]
Preview: https://github.com/luzpaz/Lattice2/blob/LGTM/README.md

**Comment by DeepSOIC** [comment]
That's interesting, but I'll look into it a bit later.

**Comment by luzpaz** [comment]
Please merge. Other workbenches are participating.

**Comment by DeepSOIC** [comment]
while it is an advertising for LGTM, it seems to point out actual errors in code for me, so I say it's a deal =)

**Comment by DeepSOIC** [comment]
It puts a poster that my code is garbage. What a shame on me!

**Pull request merged**
