### PR TITLE
Add package.xml metadata

### LINKED ISSUE #54: Update to new FreeCAD AddonManager metadata schema
Please see https://github.com/FreeCAD/FreeCAD-addons/issues/200

BTW, @DeepSOIC can you also do the same fo PartoMagic WB? :stuck_out_tongue_winking_eye:

### PR DESCRIPTION
**Pull request by luzpaz**
Closes #54  
There are some fields in the metadata that need to be updated/reviewed

### CODE REVIEW

**Comment by luzpaz** [comment]
CC @chennes can you double check?

**Comment by chennes** [comment]
The two `<tag>` elements should be inside the `<workbench>` tag, at the same level as `<subdirectory>`.

**Comment by luzpaz** [comment]
Should be good to go?

**Comment by DeepSOIC** [comment]
thank you guys!

**Pull request merged**
